### ISSUE TITLE
Create PDF form-enabled versions of four affidavits

### ISSUE THREAD

**Issue by cwulfman** [cwulfman/MarkIt-affidavit-gallery#1]
Microsoft-formatted, hand-crafted affidavits for Alaska, Nevada, Oregon, and West Virginia are in the docx directory.

**Comment by awoflaherty** [comment]
@cwulfman Is this complete?  May I use the .PDF files in this repo?

**Comment by cwulfman** [comment]
It's complete to the best of my knowledge.  I'll close the issue.
