### ISSUE TITLE
Email variable in telephone number location

### ISSUE THREAD

**Issue by awoflaherty** [cwulfman/MarkIt-affidavit-gallery#3]
Several examples (all but Alaska I think) places email where phone number should appear.  See screenshot as an example.

<img width="629" alt="phone number missing from Aff " src="https://user-images.githubusercontent.com/3749789/178738001-ef6953b1-38a5-4453-9fdc-3c72cd45b471.png">

**Comment by cwulfman** [comment]
This is not an affidavit pdf I've produced; this looks like one of the Word documents Drake Rambke provided, and that I recreated/redesigned back in April.  Have a look in the repository: https://github.com/cwulfman/MarkIt-affidavit-gallery/; and see the commit history: https://github.com/cwulfman/MarkIt-affidavit-gallery/commits/main.
