### ISSUE TITLE
Alaska affidavit should have a place for SSN4

### ISSUE THREAD

**Issue by cwulfman** [cwulfman/MarkIt-affidavit-gallery#6]
Alaska affidavit has places for a state issued number (Driver's License or State ID number) AND SSN4.  Matt reports this latest version does not have it SSN4 and add it?

**Comment by awoflaherty** [comment]
This relates to https://github.com/cwulfman/MarkIt-affidavit-gallery/issues/5 where SSN4 is listed.

**Comment by cwulfman** [comment]
That's good; then please re-open that ticket and explain why it isn't finished.
